velodyne_transform_node:
    ros__parameters:
        calibration: VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true
        # calibrate_intensities: true          # 👈 이 줄 추가
        # return_mode: "Strongest"   
